### ISSUE TITLE
Report a conflict issue between libraries：ImportError: DLL load failed while importing defs

### ISSUE THREAD

**Issue by SaaSGun** [tianyikillua/pymapping#4]
Operating System: Windows 10
Python version: 3.11
Where Python was acquired: Anaconda on Windows
h5py version: 3.11.0
HDF5 version: None

My script (just 2 import statements) is as follows:

`import pymapping`
`import h5py`

The full traceback/stack trace shown: ImportError:

Traceback (most recent call last):
File "m:\named_selections\trial.py", line 2, in
import h5py
File "M:\named_selections.conda\Lib\site-packages\h5py_init_.py", line 33, in
from . import version
File "M:\named_selections.conda\Lib\site-packages\h5py\version.py", line 15, in
from . import h5 as _h5
File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.

Describe: Hi, I am using medcoupling together with h5py
Installed h5py using -> conda install conda-forge::h5py
Installed pymapping using -> pip install pymapping

Could someone help me with this error please. thanks!

**Comment by SaaSGun** [comment]
So basically, taking following steps (as per your suggestion) helped solve my issue -

started with a clean conda virtual environment
ran the following:
conda install conda-forge::meshio
conda install conda-forge::medcoupling
pip install --no-deps pymapping (make sure pymapping gets installed in the virtual environment and not in the base environment)
